package ciserver

// Build Statuses
type Status int

// Statuses
const (
	UNKNOWN Status = iota
	SUCCESS
	FAILURE
	ABORTED
	DISABLED
	UNSTABLE
	NOT_BUILT
	BUILDING_FROM_UNKNOWN
	BUILDING_FROM_SUCCESS
	BUILDING_FROM_FAILURE
	BUILDING_FROM_ABORTED
	BUILDING_FROM_DISABLED
	BUILDING_FROM_UNSTABLE
	BUILDING_FROM_NOT_BUILT
	BUILDING_FROM_PREVIOUS_STATE
	POLL_ERROR
	INVALID_STATUS
)

var statuses = [...]string{
	"UNKNOWN",
	"SUCCESS",
	"FAILURE",
	"ABORTED",
	"DISABLED",
	"UNSTABLE",
	"NOT_BUILT",
	"BUILDING_FROM_UNKNOWN",
	"BUILDING_FROM_SUCCESS",
	"BUILDING_FROM_FAILURE",
	"BUILDING_FROM_ABORTED",
	"BUILDING_FROM_DISABLED",
	"BUILDING_FROM_UNSTABLE",
	"BUILDING_FROM_NOT_BUILT",
	"BUILDING_FROM_PREVIOUS_STATE",
	"POLL_ERROR",
	"INVALID_STATUS",
}

func (s Status) String() string {
	return statuses[s]
}
